# Generated by Django 3.1.2 on 2021-05-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Columns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('target_name', models.CharField(max_length=300)),
                ('data_type', models.CharField(max_length=300)),
                ('length', models.CharField(default='', max_length=300)),
                ('is_key', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dialect', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('server', models.CharField(max_length=300)),
                ('database', models.CharField(max_length=300)),
                ('schema', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('target_name', models.CharField(max_length=300)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
